YazilimIsi.WebApp/Models/YazilimciViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YazilimIsi.Entity.Models;

namespace YazilimIsi.WebApp.Models
{
    public class YazilimciViewModels
    {
        public Developer Developer { get; set; }
        public List<Offer> LastFiveOffers { get; set; }
        public List<Portfolio> LastFivePortfolio { get; set; }
        public List<Education> LastFiveEducations { get; set; }
        public List<string> DeveloperSkills { get; set; }
        public List<string> DeveloperAreas { get; set; }
        public List<Award> LastFiveAwards { get; set; }

        public Portfolio FormPortfolio { get; set; }
        public Award FormAward { get; set; }
        public Education FormEducation { get; set; }
    }
}

YazilimIsi.WebApp/Controllers/AnasayfaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReflectionIT.Mvc.Paging;
using YazilimIsi.Business.Abstract;
using YazilimIsi.Business.Concrete;
using YazilimIsi.DataAccess.Concrete;
using YazilimIsi.Entity.Models;
using YazilimIsi.WebApp.Models;

namespace YazilimIsi.WebApp.Controllers
{
    public class AnasayfaController : Controller
    {

        IContactService _contactService = new ContactManager(new EfContactDal());
        IJobService _jobService = new JobManager(new EfJobDal());
        IDeveloperService _developerService = new DeveloperManager(new EfDeveloperDal());
        IUserService _userService = new UserManager(new EfUserDal());
        IOfferService _offerService = new OfferManager(new EfOfferDal());
        IBlogService _blogService = new BlogManager(new EfBlogDal());

        /* Anasayfa Index Sayfasi */
        public IActionResult Index()
        {
            return View();
        }

        /* Anasayfa Nedir Sayfasi */
        public IActionResult Nedir()
        {
            return View();
        }

        /* Anasayfa NasilCalisir Sayfasi */
        public IActionResult NasilCalisir()
        {
            return View();
        }

        /* Anasayfa Gelistiriciler Sayfasi */
        public IActionResult Gelistiriciler()
        {
            return View();
        }

        /* Anasayfa SSS Sayfasi */
        public IActionResult SSS()
        {
            return View();
        }

        /* Anasayfa YazilimBlog Sayfasi */
        public IActionResult YazilimBlog()
        {
            return View(_blogService.GetAllBlogArticlesByCategory("Yazilim"));
        }

        /* Anasayfa IsVerenBlog Sayfasi */
        public IActionResult IsVerenBlog()
        {
            return View(_blogService.GetAllBlogArticlesByCategory("Isveren"));
        }

        /* Anasayfa Iletisim Sayfasi */
        public IActionResult Iletisim()
        {
            return View();
        }



        /* **************************************************************************************************************** */



        /* Anasayfa Yazilim Isleri Sayfasi */
        public IActionResult Isler(int sayfa=1, [FromQuery] string sehir = null, [FromQuery] string anahtar = null, [FromQuery] string kategori = null, [FromQuery] string type = null, [FromQuery] string minPrice = null, [FromQuery] string maxPrice = null, [FromQuery] string minTime = null, [FromQuery] string maxTime = null)
        {
            List<Job> jobs = _jobService.GetAllJobs();
            AnasayfaIslerViewModel anasayfaIslerViewModel = new AnasayfaIslerViewModel();
            if (anahtar != null)
            {
                anahtar = anahtar.ToLower();
                ViewBag.JobSearchKey = anahtar;
                jobs = jobs.Where(x => x.Title.ToLower().Contains(anahtar)).ToList();
            }
            if (sehir != null)
            {
                if (sehir != "Bütün Konumlar")
                {
                    ViewBag.JobSearchCity = sehir;
                    jobs = jobs.Where(x => x.Location == sehir).ToList();
                }
            }
            if (kategori != null)
            {
                if (kategori != "Bütün İlanlar")
                {
                    ViewBag.JobSearchCategory = kategori;
                    jobs = jobs.Where(x => x.Category == kategori).ToList();
                }
            }
            if (minTime != null && maxTime != null)
            {
                ViewBag.JobSearchMinTime = minTime;
                ViewBag.JobSearchMaxTime = maxTime;
                jobs = jobs.Where(x => x.Time >= Convert.ToInt32(minTime) && x.Time <= Convert.ToInt32(maxTime)).ToList();
            }
            if (minPrice != null && maxPrice != null)
            {
                ViewBag.JobSearchMinPrice = minPrice;
                ViewBag.JobSearchMaxPrice = maxPrice;
                jobs = jobs.Where(x => x.Price >= Convert.ToInt32(minPrice) && x.Price <= Convert.ToInt32(maxPrice)).ToList();
            }


            anasayfaIslerViewModel.Jobs = PagingList.Create(jobs, 10, sayfa);

            anasayfaIslerViewModel.MyPagingModel = PagingList.Create(jobs, 10, sayfa);

            return View(anasayfaIslerViewModel);
        }
        [HttpPost]
        public IActionResult Isler(int sayfa = 1, string city = null, string key =null, string category=null, string minPrice = null, string maxPrice = null, string minTime = null, string maxTime = null)
        {
            List<Job> jobs = _jobService.GetAllJobs();
            if (key != null)
            {
                key = key.ToLower();
                ViewBag.JobSearchKey = key;
                jobs = jobs.Where(x => x.Title.ToLower().Contains(key)).ToList();
            }
            if (city != null)
            {
                if (city != "Bütün Konumlar")
                {
                    ViewBag.JobSearchCity= city;
                    jobs = jobs.Where(x => x.Location == city).ToList();
                }
            }
            if (category != null)
            {
                if (category != "Bütün İlanlar")
                {
                    ViewBag.JobSearchCategory = category;
                    jobs = jobs.Where(x => x.Category == category).ToList();
                }
            }
            if (minTime != null && maxTime != null)
            {
                if (minTime != "0")
                {
                    ViewBag.JobSearchMinTime = minTime;
                    ViewBag.JobSearchMaxTime = maxTime;
                    jobs = jobs.Where(x => x.Time >= Convert.ToInt32(minTime) && x.Time <= Convert.ToInt32(maxTime)).ToList();
                }
            }
            if (minPrice != null && maxPrice != null)
            {
                if(minPrice != "0")
                {
                    ViewBag.JobSearchMinPrice = minPrice;
                    ViewBag.JobSearchMaxPrice = maxPrice;
                    jobs = jobs.Where(x => x.Price >= Convert.ToInt32(minPrice) && x.Price <= Convert.ToInt32(maxPrice)).ToList();
                }
            }
            AnasayfaIslerViewModel anasayfaIslerViewModel = new AnasayfaIslerViewModel();
            anasayfaIslerViewModel.Jobs = PagingList.Create(jobs, 10, sayfa);

            anasayfaIslerViewModel.MyPagingModel = PagingList.Create(jobs, 10, sayfa);

            return View(anasayfaIslerViewModel);
        }

        /* Anasayfa Yazilim Isi Detay Sayfasi */
        public IActionResult IsDetay(int Id)
        {
            AnasayfaIslerViewModel anasayfaIslerViewModel = new AnasayfaIslerViewModel();

            Job job = _jobService.GetJobById(Id);
            if (job == null)
            {
                return RedirectToAction("Hata");
            }

            int developerId;
            if (HttpContext.Session.GetString("SessionDeveloperId") != null)
            {
                developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
                anasayfaIslerViewModel.Developer = _developerService.GetDeveloperById(developerId);

                /* Yazilimci Daha Once Teklif Vermis Mi Bulma Islemi */
                List<Offer> offerList = _offerService.GetOffersByJobId(Id);
                foreach (var item in offerList)
                {
                    if(item.DeveloperId == developerId)
                    {
                        anasayfaIslerViewModel.DeveloperOffer = item;
                    }
                }

            }

            anasayfaIslerViewModel.Job = job;
            return View(anasayfaIslerViewModel);
        }

        /* Anasayfa Yazilimci Teklif Yapma Islemi */
        public IActionResult TeklifYap(int Id, AnasayfaIslerViewModel anasayfaIslerViewModel)
        {
            int developerId;
            if (HttpContext.Session.GetString("SessionDeveloperId") != null)
            {
                developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
                bool flag = true;
                foreach (var item in _offerService.GetOffersByJobId(Id))
                {
                    if (item.DeveloperId == developerId)
                    {
                        flag = false;
                    }
                }
                if (flag == true)
                {
                    Offer offer = anasayfaIslerViewModel.Offer;
                    offer.CreatedDate = DateTime.Now;
                    offer.JobId = Id;
                    offer.DeveloperId = developerId;
                    TempData["OfferMessage"] = "Başarılı Bir Şekilde Teklif Verdiniz.";
                    _offerService.Add(offer);
                }
                else
                {

                }
            }
            return RedirectToAction("IsDetay", new { Id = Id });
        }

        /* Anasayfa Yazilimci Teklif Duzenleme Islemi */
        public IActionResult TeklifDuzenle(int Id, int JobId, AnasayfaIslerViewModel anasayfaIslerViewModel)
        {
            int developerId;
            if (HttpContext.Session.GetString("SessionDeveloperId") != null)
            {
                developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
                Offer findOffer = _offerService.GetOfferById(Id);
                if (findOffer == null)
                {
                    return RedirectToAction("Hata");
                }
                findOffer.Price = anasayfaIslerViewModel.DeveloperOffer.Price;
                findOffer.Time = anasayfaIslerViewModel.DeveloperOffer.Time;
                findOffer.Description = anasayfaIslerViewModel.DeveloperOffer.Description;
                TempData["OfferMessage"] = "Başarılı Bir Şekilde Teklifi Güncellediniz.";
                _offerService.Update(findOffer);
            }
            return RedirectToAction("IsDetay", new { Id = JobId });

YazilimIsi.WebApp/Views/Anasayfa/Gelistiriciler.cshtml
@{
    ViewData["Title"] = "Gelistiriciler";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Geliştiriciler</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">
        <p>Hello World</p>
    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Anasayfa/Iletisim.cshtml
@{
    ViewData["Title"] = "Iletisim";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>İletişim</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">
        <p>Hello World</p>
    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Anasayfa/IsDetay.cshtml
@model YazilimIsi.WebApp.Models.AnasayfaIslerViewModel
@{
    ViewData["Title"] = "IsDetay";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>@Model.Job.Title</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                @if (TempData["OfferMessage"] != null)
                {
                    <blockquote class="generic-blockquote">@TempData["OfferMessage"]</blockquote>
                }
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="~/ImagesJob/@Model.Job.Photo" style="object-fit:cover;height:100%" alt="">
                            </div>
                            <div class="jobs_conetent">
                                <a href="#"><h4>@Model.Job.Title</h4></a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> @Model.Job.Location / Türkiye</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i> @Model.Job.Category</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        @Html.Raw(Model.Job.Description)
                    </div>
                </div>
                <div class="apply_job_form white-bg">
                    @if (Model.Developer != null)
                    {
                        if (Model.DeveloperOffer != null)
                        {
                            <h4>Teklifini Düzenle</h4>
                            <hr />
                            <small>* Daha Önce Bu İşe Teklif Vermişsin.</small><br /><br />
                            <form asp-controller="Anasayfa" asp-action="TeklifDuzenle" asp-route-Id="@Model.DeveloperOffer.Id" asp-route-JobId="@Model.Job.Id" method="post" enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="input_field">
                                            <label>Fiyat Teklifi</label>
                                            <input type="number" asp-for="@Model.DeveloperOffer.Price" value="@Model.DeveloperOffer.Price" placeholder="Fiyat Teklifiniz...">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="input_field">
                                            <label>Tamamlama Günü</label>
                                            <input type="number" asp-for="@Model.DeveloperOffer.Time" value="@Model.DeveloperOffer.Time" placeholder="Tamamlama Gününüz...">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="input_field">
                                            <label>Açıklama Yazısı</label>
                                            <textarea cols="30" rows="10" asp-for="@Model.DeveloperOffer.Description" value="@Model.DeveloperOffer.Description" placeholder="Teklifle İlgili Açıklama Yazınız..."></textarea>
                                        </div>
                                        <center><small>* Lütfen Burada Doğru Değerler Girdiğinizden Emin Olun.</small></center>
                                        <br />
                                    </div>
                                    <div class="col-md-12">
                                        <div class="submit_btn">
                                            <button class="boxed-btn3 w-100" type="submit">Teklifi Düzenle</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        }
                        else
                        {
                            <h4>Bu İşe Teklif Yap</h4>
                            <form asp-controller="Anasayfa" asp-action="TeklifYap" asp-route-Id="@Model.Job.Id" method="post" enctype="multipart/form-data">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="input_field">
                                            <input type="number" asp-for="Offer.Price" placeholder="Fiyat Teklifiniz...">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="input_field">
                                            <input type="number" asp-for="Offer.Time" placeholder="Tamamlama Gününüz...">
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="input_field">
                                            <textarea asp-for="Offer.Description" cols="30" rows="10" placeholder="Açıklama Yazınız..."></textarea>
                                        </div>
                                        <center><small>* Lütfen Burada Doğru Değerler Girdiğinizden Emin Olun.</small></center>
                                        <br />
                                    </div>
                                    <div class="col-md-12">
                                        <div class="submit_btn">
                                            <button class="boxed-btn3 w-100" type="submit">Teklifi Yap</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        }

                    }
                    else
                    {
                        <h5>Giriş Yapılmamış</h5>
                        <hr />
                        <p>Teklif Verebilmek İçin Lütfen <a href="/Uye/YazilimciGiris/">Giriş Yapınız</a></p>
                    }
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>İş Özeti</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Yayınlanma Tarihi: <span>@Convert.ToDateTime(Model.Job.CreatedDate).ToShortDateString()</span></li>
                            <li>Fiyat: <span>@Model.Job.Price TL</span></li>
                            <li>Tamamlanma Günü: <span>@Model.Job.Time Gün</span></li>
                            <li>Konum: <span>@Model.Job.Location</span></li>
                            <li>Kategori: <span>@Model.Job.Category</span></li>
                        </ul>
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>Paylaş:</span>
                    <ul>
                        <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                    </ul>
                </div>
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>İstatistikler</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Teklif Sayısı: <span>5</span></li>
                            <li>Ortalama Fiyat: <span>1500 TL</span></li>
                            <li>En Düşük Fiyat: <span>1200 TL</span></li>
                            <li>En Yüksek Fiyat: <span>2000 TL</span></li>
                            <li>Ortalama Süre: <span>15 Gün</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

YazilimIsi.WebApp/Views/Anasayfa/IsVerenBlog.cshtml
@model IEnumerable<YazilimIsi.Entity.Models.Blog>
@{
    ViewData["Title"] = "IsVerenBlog";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>İş Veren Blog</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">
        @if (Model.Count() > 0)
        {

            <div class="row">
                <div class="col-md-4">

                    @foreach (var item in Model)
                    {
                        <div class="card">
                            <div class="card-header">
                                @item.Title
                            </div>
                            <div class="card-body">
                                @item.Category
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
        else
        {
            <p>Henüz Yazı Eklenmemiş...</p>
        }
    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Anasayfa/Isveren.cshtml
@model YazilimIsi.Entity.Models.User
@{
    ViewData["Title"] = "Isveren";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>İşveren Profili : @Model.Name @Model.Surname</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="row text-center">
            <div class="col-md-4">

                <!-- Yazilimci Profil Fotografi -->
                <div class="card">
                    <img class="card-img-top" src="~/ImagesUser/@Model.Photo" alt="@Model.Username">
                    <p class="genric-btn info-border" style="margin:10px;">Ad Soyad: @Model.Name @Model.Surname</p>
                    <p class="genric-btn info-border" style="margin:10px;">Üyelik Tarihi: @Model.CreatedDate</p>
                    <p class="genric-btn info-border" style="margin:10px;">Şehir: @Model.City</p>
                </div>
                <br />

                <div class="card">
                    <div class="card-header">
                        İletişim Bilgileri
                    </div>
                    <div class="card-body">
                        <ul class="list-group text-left">
                            <li class="list-group-item">Ad Soyad : @Model.Name @Model.Surname</li>
                            <li class="list-group-item">Mail : @Model.Mail</li>
                            <li class="list-group-item">Şehir : @Model.City</li>
                            <li class="list-group-item">Ülke : @Model.Country</li>
                        </ul>
                    </div>
                </div>
                <br />

            </div>
            <div class="col-md-8">

                <div class="card">
                    <div class="card-header">
                        İşveren Hakkında
                    </div>
                    <div class="card-body">
                        @Model.Description
                    </div>
                </div>
                <br />

                <!-- ISVEREN ISLER -->
                <div class="card">
                    <div class="card-header">
                        Oluşturduğu İşler
                    </div>
                    <div class="card-body">
                        @if (ViewBag.UserCreatedJobs.Count > 0)
                        {
                            <ul class="list-group">
                                @foreach (var item in ViewBag.UserCreatedJobs)
                                {
                                    <li class="list-group-item"> <a style="cursor:pointer" onclick="showDetayPortfolyo('@item.Title','@item.CreatedDate','@item.Price','@item.Time','@item.Category','@item.Id')"><b>Proje Adı: </b>@item.Title</a></li>
                                }
                            </ul>
                        }
                        else
                        {
                            <p>Henüz Proje Eklenmemiş.</p>
                        }
                        <br />
                    </div>
                </div>
                <br />

            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->



<!-- Detay Portfolyo Modal -->
<div class="modal fade" id="modalDetayPortfolyo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Portfolyo Detayları</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <form asp-controller="" asp-action="" enctype="multipart/form-data">
                        <div class="form-group">
                            <label class="p-1">İş Adı</label>
                            <input id="title" name="title" type="text" class="form-control" readonly /><br />

                            <label class="p-1">Oluşturulma Tarihi</label>
                            <input id="createdDate" name="createdDate" type="text" class="form-control" readonly /> <br />

                            <div class="row">
                                <div class="col-md-6">
                                    <label class="p-1">Fiyat</label>
                                    <input id="price" name="price" type="text" class="form-control" readonly />
                                </div>
                                <div class="col-md-6">
                                    <label class="p-1">Zaman</label>
                                    <input id="time" name="time" type="text" class="form-control" readonly />
                                </div>
                            </div> <br />

                            <label class="p-1">Kategori</label>
                            <input id="category" name="category" type="text" class="form-control" readonly /> <br />
                        </div>

                        <a id="id" name="id" class="genric-btn info">Sayfayı İncele</a>
                        <button type="button" class="genric-btn danger" data-dismiss="modal">Kapat</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    function showDetayPortfolyo(title, createdDate, price, time, category, id) {
        $("#modalDetayPortfolyo #title").val(title);
        $("#modalDetayPortfolyo #createdDate").val(createdDate);
        $("#modalDetayPortfolyo #price").val(price);
        $("#modalDetayPortfolyo #time").val(time);
        $("#modalDetayPortfolyo #category").val(category);
        document.getElementById("id").href = "/Anasayfa/IsDetay/" + id;
        $("#modalDetayPortfolyo").modal();
    }
</script>

YazilimIsi.WebApp/Views/Anasayfa/NasilCalisir.cshtml
@{
    ViewData["Title"] = "NasilCalisir";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Nasıl Çalışır ?</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">
       <p>Hello World</p>
    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Anasayfa/SSS.cshtml
@{
    ViewData["Title"] = "SSS";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Sık Sorulan Sorular</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">
        <p>Hello World</p>
    </div>
</div>
<!-- featured_candidates_area_end  -->