YazilimIsi.WebApp/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using YazilimIsi.Business.Abstract;
using YazilimIsi.Business.Concrete;
using YazilimIsi.DataAccess.Concrete;
using YazilimIsi.Entity.Models;
using YazilimIsi.HelperFileUploader.Concrete;
using YazilimIsi.WebApp.Models;

namespace YazilimIsi.WebApp.Controllers
{
    public class UyeController : Controller
    {

        IDeveloperService _developerService = new DeveloperManager(new EfDeveloperDal());
        IPortfolioService _portfolioService = new PortfolioManager(new EfPortfolioDal());
        IAwardService _awardService = new AwardManager(new EfAwardDal());
        IEducationService _educationService = new EducationManager(new EfEducationDal());

        IUserService _userService = new UserManager(new EfUserDal());
        IJobService _jobService = new JobManager(new EfJobDal());
        IOfferService _offerService = new OfferManager(new EfOfferDal());
        ISupportService _supportService = new SupportManager(new EfSupportDal());

        /* Yazilimci Profil Sayfasi */
        public IActionResult YazilimciProfil()
        {
            int developerId;
            if (HttpContext.Session.GetString("SessionDeveloperId") == null)
            {
                return RedirectToAction("Index", "Anasayfa");
            }
            developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Developer developer = _developerService.GetDeveloperById(developerId);


            YazilimciViewModels yazilimciViewModels = new YazilimciViewModels();
            yazilimciViewModels.Developer = developer;
            yazilimciViewModels.LastFiveOffers = _offerService.GetOffersByDeveloperId(developerId).Take(5).ToList();
            yazilimciViewModels.LastFivePortfolio = _portfolioService.GetPortfoliosByDeveloperId(developerId).Take(5).ToList();
            yazilimciViewModels.LastFiveAwards = _awardService.GetAwardsByDeveloperId(developerId).Take(5).ToList();
            yazilimciViewModels.LastFiveEducations = _educationService.GetEducationsByDeveloperId(developerId).Take(5).ToList();

            if (developer.DeveloperSkills.Length >= 1)
            {
                yazilimciViewModels.DeveloperSkills = developer.DeveloperSkills.Split(',').ToList();
            }
            else
            {
                List<string> stringlist = new List<string>();
                yazilimciViewModels.DeveloperSkills = stringlist;
            }

            if (developer.DeveloperAreas.Length >= 1)
            {
                yazilimciViewModels.DeveloperAreas = developer.DeveloperAreas.Split(',').ToList();
            }
            else
            {
                List<string> stringlist = new List<string>();
                yazilimciViewModels.DeveloperAreas = stringlist;
            }
            return View(yazilimciViewModels);
        }

        /* IsVeren Profil Sayfasi */
        public IActionResult UyeProfil()
        {
            int userId;
            if (HttpContext.Session.GetString("SessionUserId") == null)
            {
                return RedirectToAction("Index", "Anasayfa");
            }
            userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));

            UserViewModels userViewModels = new UserViewModels();
            userViewModels.User = _userService.GetUserById(userId);
            userViewModels.UserJobs = _jobService.GetJobsByUserId(userId);

            ViewBag.UserCreatedJobsCount = _jobService.GetJobsByUserId(userId).Count.ToString();
            ViewBag.UserCreatedAndCompletedJobsCount = _jobService.GetJobsByUserId(userId).Where(x => x.IsCompleted == true).ToList().Count.ToString();
            ViewBag.UserJobsOffersCount = _offerService.GetOffersByUserId(userId).Count.ToString();
            ViewBag.UserSupportsCountByOpen = _supportService.GetSupportsByUserId(userId).Where(x => x.IsCompleted == false).ToList().Count.ToString();

            return View(userViewModels);
        }

        /* Uyeler Icin Giris Sayfasi */
        public IActionResult Giris()
        {
            return View();
        }

        /* Uye Olmak Isteyenler Icin Kayit Olma Sayfasi */
        public IActionResult UyeOl()
        {
            return View();
        }

        /* Yazilimci Giris Yapma Sayfasi */
        public IActionResult YazilimciGiris()
        {
            return View();
        }
        [HttpPost]
        public IActionResult YazilimciGiris(Developer developer)
        {
            // var userId = HttpContext.Session.GetString("SessionUserId").ToString();
            if (!_developerService.DeveloperLoginCheck(developer.Username, developer.Password))
            {
                TempData["LogInErrorMessage"] = "Kullanıcı Adını Veya Şifreyi Hatalı Girdiniz";
                return View();
            }
            var developerId = _developerService.GetAllDevelopers().Where(x => x.Username == developer.Username && x.Password == developer.Password).SingleOrDefault().Id;
            HttpContext.Session.SetString("SessionDeveloperId", developerId.ToString());
            return RedirectToAction("UyeProfil");
        }

        /* Is Veren Giris Yapma Sayfasi */
        public IActionResult IsVerenGiris()
        {
            return View();
        }
        [HttpPost]
        public IActionResult IsVerenGiris(User user)
        {
            if (!_userService.UserLoginCheck(user.Username, user.Password))
            {
                TempData["LogInErrorMessage"] = "Kullanıcı Adını Veya Şifreyi Hatalı Girdiniz";
                return View();
            }
            var userId = _userService.GetAllUsers().Where(x => x.Username == user.Username && x.Password == user.Password).SingleOrDefault().Id;
            HttpContext.Session.SetString("SessionUserId", userId.ToString());
            return RedirectToAction("YazilimciProfil");
        }

        /* Yazilimci Uye Olma Yapma Sayfasi */
        public IActionResult YazilimciUyeOl()
        {
            return View();
        }
        [HttpPost]
        public IActionResult YazilimciUyeOl(Developer developer)
        {
            if (developer.Username.Length < 1 || developer.Password.Length < 1 || developer.Mail.Length < 1)
            {
                TempData["SignInErrorMessage"] = "Lütfen Gerekli Alanları Doldurunuz";
                return View();
            }
            if (!_developerService.DeveloperUsernameCheck(developer.Username))
            {
                TempData["SignInErrorMessage"] = "Bu Kullanıcı Adı Sistemde Kullanılmaktadır. Lütfen Farklı Bir Kullanıcı Adı İle Üye Olmayı Deneyiniz.";
                return View();
            }
            if (!_developerService.DeveloperMailCheck(developer.Mail))
            {
                TempData["SignInErrorMessage"] = "Bu Mail Hesabı Sistemde Kullanılmaktadır. Lütfen Farklı Bir Mail Hesabı İle Üye Olmayı Deneyiniz.";
                return View();
            }
            developer.CreatedDate = DateTime.Now;
            developer.IsConfirm = false;
            developer.Money = "2";
            _developerService.Add(developer);
            return RedirectToAction("UyelikBasari");
        }

        /* Is Veren Uye Olma Yapma Sayfasi */
        public IActionResult IsVerenUyeOl()
        {
            return View();
        }
        [HttpPost]
        public IActionResult IsVerenUyeOl(User user)
        {
            if (user.Username.Length < 1 || user.Password.Length < 1 || user.Mail.Length < 1)
            {
                TempData["SignInErrorMessage"] = "Lütfen Gerekli Alanları Doldurunuz";
                return View();
            }
            if (!_userService.UserUsernameCheck(user.Username))
            {
                TempData["SignInErrorMessage"] = "Bu Kullanıcı Adı Sistemde Kullanılmaktadır. Lütfen Farklı Bir Kullanıcı Adı İle Üye Olmayı Deneyiniz.";
                return View();
            }
            if (!_userService.UserMailCheck(user.Mail))
            {
                TempData["SignInErrorMessage"] = "Bu Mail Hesabı Sistemde Kullanılmaktadır. Lütfen Farklı Bir Mail Hesabı İle Üye Olmayı Deneyiniz.";
                return View();
            }
            user.CreatedDate = DateTime.Now;
            user.IsConfirm = false;
            user.Money = "2";
            _userService.Add(user);
            return RedirectToAction("UyelikBasari");
        }

        /* Uye Olduktan Sonra Sayfa */
        public IActionResult UyelikBasari()
        {
            return View();
        }



        /* Uye Teknik Bildirim Olusturma Sayfasi */
        public IActionResult YeniTeknikBildirim()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> YeniTeknikBildirim(Support support, IFormFile Image)
        {
            int? userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            int? developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            if (userId == null && developerId == null)
            {
                return View("Hata");
            }
            if (support.Description.Length == 0 || support.Title.Length == 0)
            {
                return View();
            }
            support.CreatedDate = DateTime.Now;
            support.IsCompleted = false;
            if (userId != null && userId != 0)
            {
                support.Username = userId.ToString();
                support.UserType = "User";
            }
            if (developerId != null && developerId != 0)
            {
                support.Username = developerId.ToString();
                support.UserType = "Developer";
            }
            // Ek Dosya Varsa Onu Ekleme
            if (Image != null)
            {
                string guidFileName = Guid.NewGuid().ToString();

YazilimIsi.WebApp/Views/Uye/Giris.cshtml
@{
    ViewData["Title"] = "Giris";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Giriş Yap</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="row text-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <br />
                        <h3>Yazılımcılar İçin Giriş</h3>
                    </div>
                    <div class="card-body">
                        <a href="/Uye/YazilimciGiris/" class="boxed-btn3">Yazılımcı Olarak Giriş Ol</a>
                        <br /><br />
                        <p>* Yazılımcı Olarak Giriş Yaptığın Zaman Açık Bütün Yazılım İşlerine Teklif Verebilirsin.</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <br />
                        <h3>İş Verenler İçin Giriş</h3>
                    </div>
                    <div class="card-body">
                        <a href="/Uye/IsVerenGiris/" class="boxed-btn3">İş Veren Olarak Giriş Ol</a>
                        <br /><br />
                        <p>* İş Veren Olarak Giriş Yaptığın Zaman Yeni Yazılım İşleri Oluşturup Yayınlayabilirsin.</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Uye/Hata.cshtml
@{
    ViewData["Title"] = "Hata";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Hata Oluştu</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">
        <p>Hata Oluştu</p>
    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Uye/IsVerenGiris.cshtml
@model YazilimIsi.Entity.Models.User
@{
    ViewData["Title"] = "IsVerenGiris";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>İş Veren Giriş</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="col-md-8 text-center mx-auto">

            @if (TempData["LogInErrorMessage"] != null)
            {
                <blockquote class="generic-blockquote">@TempData["LogInErrorMessage"]</blockquote>
            }

            <div class="card">
                <div class="card-header">
                    <br />
                    <h3>İş Verenler İçin Giriş</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="Uye" asp-action="IsVerenGiris" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <input asp-for="Username" type="text" class="form-control" placeholder="Kullanıcı Adını Giriniz..." required>
                        </div>
                        <div class="form-group">
                            <input asp-for="Password" type="password" class="form-control" placeholder="Şifrenizi Giriniz..." required>
                        </div>
                        <button type="submit" class="boxed-btn3">İş Veren Girişi Yap</button>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Uye/IsVerenUyeOl.cshtml
@model YazilimIsi.Entity.Models.User
@{
    ViewData["Title"] = "IsVerenUyeOl";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>İş Veren Üye Ol</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="col-md-8 text-center mx-auto">

            @if (TempData["SignInErrorMessage"] != null)
            {
                <blockquote class="generic-blockquote">@TempData["SignInErrorMessage"]</blockquote>
            }

            <h3>İş Verenler İçin Üyelik</h3>
            <hr />
            <form asp-controller="Uye" asp-action="IsVerenUyeOl" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <input asp-for="Username" type="text" class="form-control" placeholder="Kullanıcı Adını Giriniz..." required>
                </div>
                <div class="form-group">
                    <input asp-for="Mail" type="email" class="form-control" placeholder="Mail Adresiniz Giriniz..." required>
                </div>
                <div class="form-group">
                    <input asp-for="Name" type="text" class="form-control" placeholder="Adınızı Giriniz..." required>
                </div>
                <div class="form-group">
                    <input asp-for="Surname" type="text" class="form-control" placeholder="Soyadınızı Giriniz..." required>
                </div>
                <div class="form-group">
                    <input asp-for="Phone" type="text" class="form-control" placeholder="Telefon Numaranızı Giriniz..." required>
                </div>
                <div class="form-group">
                    <textarea asp-for="Address" class="form-control" placeholder="Adresinizi Giriniz..." rows="4" required></textarea>
                </div>
                <div class="form-group">
                    <input asp-for="Password" type="password" class="form-control" placeholder="Şifrenizi Giriniz..." required>
                </div>
                <button type="submit" class="boxed-btn3">İş Veren Üyeliği Oluştur</button>
            </form>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Uye/TeknikBildirimDetay.cshtml
@model YazilimIsi.Entity.Models.Support
@{
    ViewData["Title"] = "TeknikBildirimDetay";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Teknik Bildirim Detaylar</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="card text-center">
            <div class="card-body">
                <h3>Teknik Bildirim Detayları</h3>
                <hr />
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Başlık</td>
                            <td>@Model.Title</td>
                        </tr>
                        <tr>
                            <td>Kategori</td>
                            <td>@Model.Category</td>
                        </tr>
                        <tr>
                            <td>Oluşturulma Tarihi</td>
                            <td>@Model.CreatedDate</td>
                        </tr>
                        <tr>
                            <td>Tamamlanma Durumu</td>
                            <td>@Model.IsCompleted</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>Teknik Bildirim Açıklama Yazısı</h3>
                <hr />
                <p>@Model.Description</p>
            </div>
        </div>
        <br />
        @if (Model.SupportFile != null)
        {
            <div class="card text-center">
                <div class="card-body">
                    <h3>Teknik Bildirim Ek Dosya</h3>
                    <hr />
                    <p>Teknik Bildirim Ek Dosya Adı</p>
                    <p>@Model.SupportFile</p>
                </div>
            </div>
            <br />
        }

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Uye/YazilimciGiris.cshtml
@model YazilimIsi.Entity.Models.Developer
@{
    ViewData["Title"] = "YazilimciGiris";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Yazılımcı Giriş</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="col-md-8 text-center mx-auto">

            @if (TempData["LogInErrorMessage"] != null)
            {
                <blockquote class="generic-blockquote">@TempData["LogInErrorMessage"]</blockquote>
            }

            <div class="card">
                <div class="card-header">
                    <br />
                    <h3>Yazılımcılar İçin Giriş</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="Uye" asp-action="YazilimciGiris" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <input asp-for="Username" type="text" class="form-control" placeholder="Kullanıcı Adını Giriniz..." required>
                        </div>
                        <div class="form-group">
                            <input asp-for="Password" type="password" class="form-control" placeholder="Şifrenizi Giriniz..." required>
                        </div>
                        <button type="submit" class="boxed-btn3">Yazılımcı Girişi Yap</button>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Uye/YazilimciUyeOl.cshtml
@model YazilimIsi.Entity.Models.Developer
@{
    ViewData["Title"] = "YazilimciUyeOl";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Yazılımcı Üye Ol</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="col-md-8 text-center mx-auto">

            @if (TempData["SignInErrorMessage"] != null)
            {
                <blockquote class="generic-blockquote">@TempData["SignInErrorMessage"]</blockquote>
            }

            <h3>Yazılımcılar İçin Üyelik</h3>
            <hr />
            <form asp-controller="Uye" asp-action="YazilimciUyeOl" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <input asp-for="Username" type="text" class="form-control" placeholder="Kullanıcı Adını Giriniz..." required>
                </div>
                <div class="form-group">
                    <input asp-for="Mail" type="email" class="form-control" placeholder="Mail Adresiniz Giriniz..." required>
                </div>
                <div class="form-group">
                    <input asp-for="Name" type="text" class="form-control" placeholder="Adınızı Giriniz..." required>
                </div>
                <div class="form-group">
                    <input asp-for="Surname" type="text" class="form-control" placeholder="Soyadınızı Giriniz..." required>
                </div>
                <div class="form-group">
                    <input asp-for="Phone" type="text" class="form-control" placeholder="Telefon Numaranızı Giriniz..." required>
                </div>
                <div class="form-group">
                    <textarea asp-for="Address" class="form-control" placeholder="Adresinizi Giriniz..." rows="4" required></textarea>
                </div>
                <div class="form-group">
                    <input asp-for="Password" type="password" class="form-control" placeholder="Şifrenizi Giriniz..." required>
                </div>
                <button type="submit" class="boxed-btn3">Yazılımcı Üyeliği Oluştur</button>
            </form>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Uye/YeniTeknikBildirim.cshtml
@model YazilimIsi.Entity.Models.Support
@{
    ViewData["Title"] = "YeniTeknikBildirim";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Yeni Teknik Bildirim Oluştur</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container text-center">

        @if (TempData["AddErrorMessage"] != null)
        {
            <blockquote class="generic-blockquote">@TempData["AddErrorMessage"]</blockquote>
        }

        <form asp-controller="Uye" asp-action="YeniTeknikBildirim" method="post" enctype="multipart/form-data">

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Yeni Teknik Bildirim Oluşturma Ekranına Hoşgeldin</h5>
                    <hr />
                    <p class="card-text">Teknik Bildirimin İle İlgili Detay Verirken Lütfen Bütün Alanları Doldurmaya Çalış.</p>
                    <p class="card-text">Gönderilen Bildirimlerin İncelenmesinin Ardından En Kısa Sürede Size Geri Dönüş Sağlanır.</p>
                </div>
            </div>
            <br />

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Teknik Bildirim Başlığı</h5>
                    <hr />
                    <div class="form-group col-md-8 mx-auto">
                        <input type="text" asp-for="Title" class="form-control" placeholder="Teknik Bildirim Başlığını Giriniz..." required>
                        <small>* Lütfen Teknik Bildirim Başlığı Belirtirken Açıklayıcı Ve Kısa Olmaya Çalışın.</small>
                    </div>
                </div>
            </div>
            <br />

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Teknik Bildirim Kategori Seçimi</h5>
                    <hr />
                    <div class="form-group col-md-8 mx-auto">
                        <select asp-for="Category">
                            <option>Tüm Teknik Bildirimler Kategorisi</option>
                            <option>Frontend Yazılım</option>
                            <option>Backend Yazılım</option>
                            <option>Full Stack Yazılım</option>
                            <option>Mobil Uygulama Geliştirme</option>
                            <option>Masaüstü Uygulama Geliştirme</option>
                            <option>Gömülü Sistem Yazılımı</option>
                            <option>Veritabanı Programcılığı</option>
                            <option>Oyun Geliştirme</option>
                        </select>
                    </div>
                </div>
            </div>
            <br />

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Teknik Bildirim Ek Dosya</h5>
                    <hr />
                    <div class="form-group col-md-8 mx-auto">
                        <input class="form-control" type="file" name="Image" />
                        <small>* Teknik Bildirim İle İlgili Eklemek İstediğiniz Dosya Varsa Ekleyebilirsiniz.</small>
                    </div>
                </div>
            </div>
            <br />

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Teknik Bildirim Açıklama Yazısı</h5>
                    <hr />
                    <div class="form-group col-md-8 mx-auto">
                        <small>* Lütfen Teknik Bildirim İle İlgili Detaylı Ve Açıklayıcı Bir Tanıtım Yazısı Giriniz</small>
                        <textarea asp-for="Description" class="form-control" placeholder="Teknik Bildirim Tanıtım Yazısını Giriniz..." rows="8" required></textarea>
                    </div>
                </div>
            </div>
            <br />

            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Teknik Bildirim İşlemler</h5>
                    <hr />
                    <div class="form-group col-md-8 mx-auto">
                        <br />
                        <button type="submit" class="genric-btn info">Teknik Bildirim Oluştur Ve Gönder</button>
                        <br /><br />
                        <small>* Teknik Bildirim Onaylandıktan Sonra Mail Adresinize Bilgi Mesajı Gönderilecektir.</small>
                    </div>
                </div>
            </div>
            <br />

        </form>
    </div>
</div>
<!-- featured_candidates_area_end  -->