YazilimIsi.WebApp/Controllers/IsverenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using YazilimIsi.Business.Abstract;
using YazilimIsi.Business.Concrete;
using YazilimIsi.DataAccess.Concrete;
using YazilimIsi.Entity.Models;
using YazilimIsi.HelperFileUploader.Concrete;
using YazilimIsi.WebApp.Models;

namespace YazilimIsi.WebApp.Controllers
{
    public class IsverenController : Controller
    {

        IUserService _userService = new UserManager(new EfUserDal());
        IJobService _jobService = new JobManager(new EfJobDal());
        IOfferService _offerService = new OfferManager(new EfOfferDal());
        ISupportService _supportService = new SupportManager(new EfSupportDal());
        IAccountActivityService _accountActivityService = new AccountActivityManager(new EfAccountActivityDal());

        /* Isveren Yeni Is Olusturma */
        public IActionResult YeniIsOlustur()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> YeniIsOlustur(Job job, IFormFile Image)
        {
            // İş Veren Bakiyesinden 1 TL Dusme
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            User user = _userService.GetUserById(userId);
            int userMoney = Convert.ToInt32(user.Money);
            if (userMoney < 1)
            {
                TempData["AddErrorMessage"] = "Hesabınızda Yeni Bir İlan Oluşturmak İçin Yeterli Bakiye Yoktur.";
                return View();
            }
            userMoney = userMoney - 1;
            user.Money = userMoney.ToString();
            _userService.Update(user);

            // Hesap Hareketlerine Bu Islemi Yazdirma
            AccountActivity accountActivity = new AccountActivity();
            accountActivity.Title = "İş İlanı Oluşturma Gideri";
            accountActivity.Description = "İş İlanı Oluşturulduğu İçin Hesabınızdan 1 TL Alınmıştır.";
            accountActivity.CreatedDate = DateTime.Now;
            accountActivity.IsIncrease = false;
            accountActivity.UserId = userId;
            accountActivity.Money = "1";
            _accountActivityService.Add(accountActivity);

            // Yeni Is İlanı Olusturma
            if (job.Title.Length == 0 || job.Description.Length == 0)
            {
                TempData["AddErrorMessage"] = "Lütfen Boş Alanları Doldurunuz.";
                return View();
            }

            job.CreatedDate = DateTime.Now;
            job.ViewCount = "0";
            job.UserId = userId;
            job.IsConfirm = false;
            job.IsCompleted = false;

            // Is Ilani Resim Kaydetme
            string guidImageName = Guid.NewGuid().ToString();
            if (await KurnazFileUploader.UploadFile(Image, guidImageName, "ImagesJob") == true)
            {
                job.Photo = guidImageName + Image.FileName;
            }

            _jobService.Add(job);

            TempData["AddSuccessMessage"] = "Oluşturduğunuz İlan Başarılı Bir Şekilde Sisteme Gönderildi. İnceleme İşlemlerinin Ardından Tarafınıza Bilgi Mesajı Gönderilecektir.";
            return RedirectToAction("UyeProfil","Uye");
        }

        /* Isveren Isleri Goruntuleme */
        public IActionResult Isler()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            var userJobs = _jobService.GetJobsByUserId(userId);
            IsverenIslerViewModel isverenIslerViewModel = new IsverenIslerViewModel();
            isverenIslerViewModel.UserJobs = userJobs;
            isverenIslerViewModel.JobOfferCounts = _offerService.GettAllOffers();
            return View(isverenIslerViewModel);
        }

        /* Isveren Is Detayi Goruntuleme */
        public IActionResult IsDetay(int Id)
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            Job job = _jobService.GetJobById(Id);
            if (job == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (job.UserId != userId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            IsverenIsDetayViewModel isverenIsDetayViewModel = new IsverenIsDetayViewModel();
            isverenIsDetayViewModel.Job = job;
            isverenIsDetayViewModel.User = null;
            isverenIsDetayViewModel.Offers = _offerService.GetOffersByJobId(job.Id);
  
            return View(isverenIsDetayViewModel);
        }

        /* Isveren Ise Gelen Teklifi Goruntuleme */
        public IActionResult TeklifDetay(int Id)
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            var offer = _offerService.GetOfferById(Id);
            if (offer == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if(offer.Job.UserId != userId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            return View(offer);
        }

        /* Ilan Yayindan Kaldirma */
        public IActionResult YayindanKaldir(int Id)
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            Job job = _jobService.GetJobById(Id);
            if (job == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (job.UserId != userId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            job.IsCompleted = true;
            _jobService.Update(job);
            TempData["UpdateSuccessMessage"] = "İlanınız Yayından Başarıyla Kaldırıldı.";
            return RedirectToAction("UyeProfil", "Uye");
        }

        /* Ilan Tamamlama */
        public IActionResult Tamamlandir(int Id)
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            Job job = _jobService.GetJobById(Id);
            if (job == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (job.UserId != userId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            job.IsCompleted = true;
            _jobService.Update(job);
            TempData["UpdateSuccessMessage"] = "İlanınız Yayından Başarıyla Kaldırıldı.";
            return RedirectToAction("UyeProfil", "Uye");
        }

        /* Ilan Teklif Sikayet Etme */
        [HttpPost]
        public IActionResult TeklifSikayet(string Description)
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            Support support = new Support();
            if (Description.Length < 10)
            {
                return View();
            }
            support.Title = "Yazılım Teklif Şikayeti";
            support.Description = Description;
            support.Category = "Teklif Şikayet";
            support.CreatedDate = DateTime.Now;
            support.IsCompleted = false;
            support.Username = userId.ToString();
            support.UserType = "User";
            _supportService.Add(support);
            TempData["AddSuccessMessage"] = "Oluşturduğunuz Şikayet Metni Başarıyla Gönderildi.";
            return RedirectToAction("UyeProfil", "Uye");
        }

        /* Isveren Hesap Hareketleri Sayfasi */
        public IActionResult HesapHareketleri()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            List<AccountActivity> activities = _accountActivityService.GetAllAccountActivitiesByUserId(userId);
            return View(activities);
        }

        /* Isveren Hesap Hareketi Detay Sayfasi */
        public IActionResult HesapHareketDetay(int Id)
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            AccountActivity accountActivity = _accountActivityService.GetAccountActivityById(Id);
            if (accountActivity == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (accountActivity.UserId != userId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            return View(accountActivity);
        }



        /* Isveren Profil Duzenleme Islemi */
        public IActionResult ProfilDuzenle()
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            User user = _userService.GetUserById(userId);
            if (user == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            return View(user);
        }

        [HttpPost]
        public IActionResult DuzenleSifre(int Id, string EskiSifre, string YeniSifre1, string YeniSifre2)
        {
            int userId = Convert.ToInt32(HttpContext.Session.GetString("SessionUserId"));
            if (userId != Id)
            {
                return RedirectToAction("Hata", "Uye");
            }
            User user = _userService.GetUserById(userId);
            if(user.Password == EskiSifre)
            {
                if(YeniSifre1 == YeniSifre2)
                {
                    user.Password = YeniSifre1;
                    _userService.Update(user);
                }
                else
                {
                    TempData["UpdateErrorMessage"] = "Girdiğiniz Şifreler Birbiriyle Aynı Değil.";
                    return RedirectToAction("ProfilDuzenle");
                }
            }
            else
            {
                TempData["UpdateErrorMessage"] = "Eski Şifrenizi Yanlış Girdiniz.";
                return RedirectToAction("ProfilDuzenle");
            }

            TempData["AddSuccessMessage"] = "Şifre Başarıyla Güncellendi.";
            return RedirectToAction("UyeProfil", "Uye");

YazilimIsi.WebApp/Views/Isveren/FotografDuzenle.cshtml
@model YazilimIsi.Entity.Models.User
@{
    ViewData["Title"] = "FotografDuzenle";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Fotoğraf Düzenleme Sayfası</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        @if (TempData["UpdateErrorMessage"] != null)
        {
            <blockquote class="generic-blockquote">@TempData["UpdateErrorMessage"]</blockquote>
        }

        <div class="row text-center">

            <div class="col-md-4">

                <!-- Uye Profil Fotografi -->
                <div class="card">
                    <img class="card-img-top" src="~/ImagesUser/@Model.Photo" alt="@Model.Username" />
                    <div class="card-body">

                        <a href="/Isveren/ProfilDuzenle/" class="genric-btn info-border">Profili Düzenle</a>

                    </div>
                </div>
                <br />
                <!-- Bakiye Ve Para Yükleme -->
                <div class="card">
                    <div class="card-body">

                        <h3>Bakiye</h3>
                        <hr />

                        <p>@Model.Money TL</p>

                        <a href="#" class="genric-btn info-border">Para Yükleme</a> <br /><br />
                        <a href="/Isveren/HesapHareketleri/" class="genric-btn info-border">Hesap Hareketlerini İncele</a>

                    </div>
                </div>
            </div>
            <div class="col-md-8">

                <!-- TEMEL PROFIL DUZENLEME -->
                <div class="card">
                    <div class="card-body">

                        <h3>Temel Profil Bilgileri</h3>
                        <hr />

                        <form asp-controller="Isveren" asp-action="FotografDuzenle" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                            <div class="form-group col-md-8 mx-auto">
                                <label>İşveren Aktif Fotoğraf</label><br />
                                <img src="~/ImagesUser/@Model.Photo" width="250" />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>İşveren Aktif Fotoğraf İsmi</label>
                                <input class="form-control" type="text" value="@Model.Photo" readonly />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>İşveren Yeni Fotoğraf</label>
                                <input class="form-control" type="file" name="Image" required />
                                <small>* Lütfen Yeni Yüklenecek Fotoğrafınızı Seçiniz.</small>
                            </div>
                            <button type="submit" class="genric-btn info-border">Fotoğrafı Güncelle</button>
                        </form>
                        <br />
                    </div>
                </div>
                <br />


            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Isveren/HesapHareketDetay.cshtml
@model YazilimIsi.Entity.Models.AccountActivity
@{
    ViewData["Title"] = "HesapHareketDetay";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Hesap Hareketi Detayları</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="card text-center">
            <div class="card-body">
                <h3>Hesap Hareket Detayı</h3>
                <hr />
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Hareket Başlığı</td>
                            <td>@Model.Title</td>
                        </tr>
                        <tr>
                            <td>Hareket Oluşturulma Tarihi</td>
                            <td>@Convert.ToDateTime(Model.CreatedDate).ToShortDateString()</td>
                        </tr>
                        <tr>
                            <td>Hareket Durumu</td>
                            <td>
                                @if(Model.IsIncrease == true)
                                {
                                    <span>+ (Gelir)</span>
                                }
                                else
                                {
                                    <span>- (Gider)</span>
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>Hareket Miktarı</td>
                            <td>@Model.Money TL</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>Hareket Açıklama Yazısı</h3>
                <hr />
                <p>@Model.Description</p>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>İşlemler</h3>
                <hr />
                <a href="/Isveren/HesapHareketleri" class="genric-btn info-border">Geriye Dön</a><br />
            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Isveren/ProfilDuzenle.cshtml
@model YazilimIsi.Entity.Models.User
@{
    ViewData["Title"] = "ProfilDuzenle";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Profil Düzenleme Sayfası</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        @if (TempData["UpdateErrorMessage"] != null)
        {
            <blockquote class="generic-blockquote">@TempData["UpdateErrorMessage"]</blockquote>
        }

        <div class="row text-center">

            <div class="col-md-4">

                <!-- Uye Profil Fotografi -->
                <div class="card">
                    <img class="card-img-top" src="~/ImagesUser/@Model.Photo" alt="@Model.Username"  />
                    <div class="card-body">

                        <a href="/Isveren/FotografDuzenle/" class="genric-btn info-border">Fotoğrafı Düzenle</a>

                    </div>
                </div>
                <br />
                <!-- Bakiye Ve Para Yükleme -->
                <div class="card">
                    <div class="card-body">

                        <h3>Bakiye</h3>
                        <hr />

                        <p>@Model.Money TL</p>

                        <a href="#" class="genric-btn info-border">Para Yükleme</a> <br /><br />
                        <a href="/Isveren/HesapHareketleri/" class="genric-btn info-border">Hesap Hareketlerini İncele</a>

                    </div>
                </div>
            </div>
            <div class="col-md-8">


                <!-- TEMEL PROFIL DUZENLEME -->
                <div class="card">
                    <div class="card-body">

                        <h3>Temel Profil Bilgileri</h3>
                        <hr />

                        <form asp-controller="Isveren" asp-action="DuzenleTemel" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                            <div class="form-group col-md-8 mx-auto">
                                <label>İşveren Adı</label>
                                <input type="text" asp-for="Name" class="form-control" value="@Model.Name" required />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>İşveren Soyadı</label>
                                <input type="text" asp-for="Surname" class="form-control" value="@Model.Surname" required />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>İşveren İş</label>
                                <input type="text" asp-for="Job" class="form-control" value="@Model.Job" required />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>İşveren Mail Adresi</label>
                                <input type="text" asp-for="Mail" class="form-control" value="@Model.Mail" readonly />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>İşveren Telefon Numarası</label>
                                <input type="text" asp-for="Phone" class="form-control" value="@Model.Phone" required />
                            </div>
                            <button type="submit" class="genric-btn info-border">Bilgileri Güncelle</button>
                        </form>
                        <br />
                    </div>
                </div>
                <br />

                <!-- ACIKLAMA PROFIL DUZENLEME -->
                <div class="card">
                    <div class="card-body">

                        <h3>Açıklama Yazısı Düzenleme</h3>
                        <hr />

                        <form asp-controller="Isveren" asp-action="DuzenleAciklama" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                            <div class="form-group col-md-8 mx-auto">
                                <label>Açıklama Yazısı</label>
                                <textarea asp-for="Description" class="form-control" rows="6" required>@Model.Description</textarea>
                            </div>
                            <button type="submit" class="genric-btn info-border">Bilgileri Güncelle</button>
                        </form>
                        <br />
                    </div>
                </div>
                <br />

                <!-- ADRES PROFIL DUZENLEME -->
                <div class="card">
                    <div class="card-body">

                        <h3>Adres Bilgileri Düzenleme</h3>
                        <hr />

                        <form asp-controller="Isveren" asp-action="DuzenleAdres" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                            <div class="form-group col-md-8 mx-auto">
                                <label>Ülke</label><br />
                                <select class="form-control" asp-for="Country" required>
                                    <option>Türkiye</option>
                                </select><br /><br />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>Şehir</label>
                                <input type="text" asp-for="City" class="form-control" value="@Model.City" required />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>Adres</label>
                                <textarea asp-for="Address" class="form-control" rows="5" required>@Model.Address</textarea>
                            </div>
                            <button type="submit" class="genric-btn info-border">Bilgileri Güncelle</button>
                        </form>
                        <br />
                    </div>
                </div>
                <br />

                <!-- SIFRE DUZENLEME -->
                <div class="card">
                    <div class="card-body">

                        <h3>Şifre Düzenleme</h3>
                        <hr />

                        <form asp-controller="Isveren" asp-action="DuzenleSifre" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                            <div class="form-group col-md-8 mx-auto">
                                <label>Eski Şifre</label>
                                <input type="text" id="EskiSifre" name="EskiSifre" class="form-control" placeholder="Eski Şifrenizi Giriniz..." required />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>Yeni Şifre</label>
                                <input type="text" id="YeniSifre1" name="YeniSifre1" class="form-control" placeholder="Yeni Şifrenizi Giriniz..." required />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>Yeni Şifre Tekrar</label>
                                <input type="text" id="YeniSifre2" name="YeniSifre2" class="form-control" placeholder="Yeni Şifrenizi Tekrar Giriniz..." required />
                            </div>
                            <button type="submit" class="genric-btn info-border">Şifre Güncelle</button>
                        </form>
                        <br />
                    </div>
                </div>
                <br />

            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Isveren/TeklifDetay.cshtml
@model YazilimIsi.Entity.Models.Offer
@{
    ViewData["Title"] = "TeklifDetay";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Teklif Detayı İnceleme</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="card text-center">
            <div class="card-body">
                <h3>Teklif Detayı</h3>
                <hr />
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>İlgili İş İlanı</td>
                            <td>@Model.Job.Title</td>
                        </tr>
                        <tr>
                            <td>Yazılımcı</td>
                            <td>@Model.Developer.Name @Model.Developer.Surname</td>
                        </tr>
                        <tr>
                            <td>Teklif Fiyatı</td>
                            <td>@Model.Price TL</td>
                        </tr>
                        <tr>
                            <td>Teklif Süresi</td>
                            <td>@Model.Time Gün</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>Teklif Açıklama Yazısı</h3>
                <hr />
                <p>@Model.Description</p>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>Yazılımcı Profili Ve Bilgiler</h3>
                <hr />
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Ad Soyad</td>
                            <td>@Model.Developer.Name @Model.Developer.Surname</td>
                        </tr>
                        <tr>
                            <td>Fotoğraf</td>
                            <td>@Model.Developer.Photo</td>
                        </tr>
                        <tr>
                            <td>Mail</td>
                            <td>@Model.Developer.Mail</td>
                        </tr>
                        <tr>
                            <td>Telefon</td>
                            <td>@Model.Developer.Phone</td>
                        </tr>
                        <tr>
                            <td>Şehir</td>
                            <td>@Model.Developer.City</td>
                        </tr>
                        <tr>
                            <td>Üyelik Tarihi</td>
                            <td>@Model.Developer.CreatedDate</td>
                        </tr>
                        <tr>
                            <td>Sosyal Medya</td>
                            <td>
                                @if (Model.Developer.MediaWebsite != null)
                                {
                                    <a href="@Model.Developer.MediaWebsite" target="_blank" style="margin-right:10px;"><i class="fa fa-laptop" style="font-size:20px;" aria-hidden="true"></i></a>
                                }
                                @if (Model.Developer.MediaGithub != null)
                                {
                                    <a href="@Model.Developer.MediaGithub" target="_blank" style="margin-right:10px;"><i class="fa fa-github" style="font-size:20px;" aria-hidden="true"></i></a>
                                }
                                @if (Model.Developer.MediaLinkedin != null)
                                {
                                    <a href="@Model.Developer.MediaLinkedin" target="_blank" style="margin-right:10px;"><i class="fa fa-linkedin" style="font-size:20px;" aria-hidden="true"></i></a>
                                }
                                @if (Model.Developer.MediaMedium != null)
                                {
                                    <a href="@Model.Developer.MediaMedium" target="_blank" style="margin-right:10px;"><i class="fa fa-medium" style="font-size:20px;" aria-hidden="true"></i></a>
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>Çalışma Alanları</td>
                            <td>@Model.Developer.DeveloperAreas</td>
                        </tr>
                        <tr>
                            <td>Yetenekleri</td>
                            <td>@Model.Developer.DeveloperSkills</td>
                        </tr>
                        <tr>
                            <td>Detaylı Profil</td>
                            <td>
                                <a href="/Yazilimci/Profil/@Model.Id" class="btn btn-outline-info btn-sm">İncele</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>İşlemler</h3>
                <hr />
                <a href="/Isveren/Isler" class="genric-btn info-border">Yazılımcıya Mail Gönder</a><br /><br />
                <a href="/Isveren/Isler" data-toggle="modal" data-target="#modalSikayetEt" class="genric-btn danger-border">Teklifi Şikayet Et</a>
            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

<!-- Modal -->
<div class="modal fade" id="modalSikayetEt" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Teklifi Şikayet Et</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Bu İlanı Gerçekten Şikayet Etmek İstiyor Musun?
            </div>
            <div class="modal-footer">
                <div class="container">
                    <form asp-controller="Isveren" asp-action="TeklifSikayet" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <textarea id="Description" name="Description" class="form-control" rows="6" placeholder="Şikayet Metninizi Giriniz..." minlength="10" required></textarea>
                        </div>
                        <button type="button" class="genric-btn info" data-dismiss="modal">Kapat</button>
                        <button type="submit" class="genric-btn danger">Şikayet Et</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>