YazilimIsi.WebApp/Models/YazilimciViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YazilimIsi.Entity.Models;

namespace YazilimIsi.WebApp.Models
{
    public class YazilimciViewModels
    {
        public Developer Developer { get; set; }
        public List<Offer> LastFiveOffers { get; set; }
        public List<Portfolio> LastFivePortfolio { get; set; }
        public List<Education> LastFiveEducations { get; set; }
        public List<string> DeveloperSkills { get; set; }
        public List<string> DeveloperAreas { get; set; }
        public List<Award> LastFiveAwards { get; set; }

        public Portfolio FormPortfolio { get; set; }
        public Award FormAward { get; set; }
        public Education FormEducation { get; set; }
    }
}

YazilimIsi.WebApp/Controllers/YazilimciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using YazilimIsi.Business.Abstract;
using YazilimIsi.Business.Concrete;
using YazilimIsi.DataAccess.Concrete;
using YazilimIsi.Entity.Models;
using YazilimIsi.HelperFileUploader.Concrete;
using YazilimIsi.WebApp.Models;

namespace YazilimIsi.WebApp.Controllers
{
    public class YazilimciController : Controller
    {

        IDeveloperService _developerService = new DeveloperManager(new EfDeveloperDal());
        IPortfolioService _portfolioService = new PortfolioManager(new EfPortfolioDal());
        IAwardService _awardService = new AwardManager(new EfAwardDal());
        IEducationService _educationService = new EducationManager(new EfEducationDal());

        IJobService _jobService = new JobManager(new EfJobDal());
        IOfferService _offerService = new OfferManager(new EfOfferDal());
        ISupportService _supportService = new SupportManager(new EfSupportDal());
        IAccountActivityService _accountActivityService = new AccountActivityManager(new EfAccountActivityDal());

        /* Yazilimci Herkese Acik Profil */
        public IActionResult Profil(int Id)
        {
            return View();
        }



        /* Yazilimci Verdigi Teklifler Listesi */
        public IActionResult Teklifler()
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            List<Offer> offers = _offerService.GetOffersByDeveloperId(developerId);
            return View(offers);
        }

        /* Yazilimci Verdigi Teklif Detayi */
        public IActionResult TeklifDetay(int Id)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Offer offer = _offerService.GetOfferById(Id);
            if (offer == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if(offer.DeveloperId != developerId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            return View(offer);
        }



        /* Yazilimci Portfolyo Listesi */
        public IActionResult Portfolyo()
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            List<Portfolio> portfolyo = _portfolioService.GetPortfoliosByDeveloperId(developerId);
            return View(portfolyo);
        }

        /* Yazilimci Portfolyo Detay Detayi */
        public IActionResult PortfolyoDetay(int Id)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Portfolio portfolyo = _portfolioService.GetPortfolioById(Id);
            if (portfolyo == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (portfolyo.DeveloperId != developerId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            return View(portfolyo);
        }

        /* Yazilimci Portfolyo Ekleme Islemi */
        [HttpPost]
        public IActionResult PortfolyoEkle(YazilimciViewModels yazilimciViewModels)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            if (yazilimciViewModels.FormPortfolio.ProjectName.Length > 1 && yazilimciViewModels.FormPortfolio.Description.Length > 5)
            {
                yazilimciViewModels.FormPortfolio.DeveloperId = developerId;
                _portfolioService.Add(yazilimciViewModels.FormPortfolio);
            }
            TempData["AddSuccessMessage"] = "Portfolyo Ekleme Başarıyla Gerçekleştirildi.";
            return RedirectToAction("YazilimciProfil", "Uye");
        }

        /* Yazilimci Portfolyo Duzenleme Islemi */
        [HttpPost]
        public IActionResult PortfolyoDuzenle(int Id, Portfolio portfolio)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Portfolio findPortfolio = _portfolioService.GetPortfolioById(Id);
            if (findPortfolio == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (findPortfolio.DeveloperId != developerId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            findPortfolio.ProjectName = portfolio.ProjectName;
            findPortfolio.Description = portfolio.Description;
            findPortfolio.CreatedDate = portfolio.CreatedDate;
            findPortfolio.ProjectUrl = portfolio.ProjectUrl;
            _portfolioService.Update(findPortfolio);
            TempData["AddSuccessMessage"] = "Portfolyo Düzenleme Başarıyla Gerçekleştirildi.";
            return RedirectToAction("YazilimciProfil", "Uye");
        }

        /* Yazilimci Portfolyo Silme Islemi */
        public IActionResult PortfolyoSil(int Id)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Portfolio portfolyo = _portfolioService.GetPortfolioById(Id);
            if (portfolyo == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (portfolyo.DeveloperId != developerId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            _portfolioService.Delete(portfolyo);
            TempData["AddSuccessMessage"] = "Portfolyo Silme Başarıyla Gerçekleştirildi.";
            return RedirectToAction("YazilimciProfil", "Uye");
        }



        /* Yazilimci Oduller Listesi */
        public IActionResult Oduller()
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            List<Award> awards = _awardService.GetAwardsByDeveloperId(developerId);
            return View(awards);
        }

        /* Yazilimci Odul Detay Detayi */
        public IActionResult OdulDetay(int Id)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Award award = _awardService.GetAwardById(Id);
            if (award == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (award.DeveloperId != developerId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            return View(award);
        }

        /* Yazilimci Odul Ekleme Islemi */
        [HttpPost]
        public IActionResult OdulEkle(YazilimciViewModels yazilimciViewModels)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            if (yazilimciViewModels.FormAward.Title.Length > 1 && yazilimciViewModels.FormAward.Description.Length > 5)
            {
                yazilimciViewModels.FormAward.DeveloperId = developerId;
                _awardService.Add(yazilimciViewModels.FormAward);
            }
            TempData["AddSuccessMessage"] = "Ödül Ekleme Başarıyla Gerçekleştirildi.";
            return RedirectToAction("YazilimciProfil", "Uye");
        }

        /* Yazilimci Odul Duzenleme Islemi */
        [HttpPost]
        public IActionResult OdulDuzenle(int Id, Award award)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Award findAward = _awardService.GetAwardById(Id);
            if (findAward == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (findAward.DeveloperId != developerId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            findAward.Title = award.Title;
            findAward.Description = award.Description;
            findAward.Date = award.Date;
            _awardService.Update(findAward);
            TempData["AddSuccessMessage"] = "Ödül Düzenleme Başarıyla Gerçekleştirildi.";
            return RedirectToAction("YazilimciProfil", "Uye");
        }

        /* Yazilimci Odul Silme Islemi */
        public IActionResult OdulSil(int Id)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Award award = _awardService.GetAwardById(Id);
            if (award == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (award.DeveloperId != developerId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            _awardService.Delete(award);
            TempData["AddSuccessMessage"] = "Ödül Silme Başarıyla Gerçekleştirildi.";
            return RedirectToAction("YazilimciProfil", "Uye");
        }

        

        /* Yazilimci Egitimler Listesi */
        public IActionResult Egitim()
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            List<Education> educations = _educationService.GetEducationsByDeveloperId(developerId);
            return View(educations);
        }

        /* Yazilimci Egitim Detay Detayi */
        public IActionResult EgitimDetay(int Id)
        {
            int developerId = Convert.ToInt32(HttpContext.Session.GetString("SessionDeveloperId"));
            Education education = _educationService.GetEducationById(Id);
            if (education == null)
            {
                return RedirectToAction("Hata", "Uye");
            }
            if (education.DeveloperId != developerId)
            {
                return RedirectToAction("Hata", "Uye");
            }
            return View(education);
        }

        /* Yazilimci Egitim Ekleme Islemi */
        [HttpPost]
        public IActionResult EgitimEkle(YazilimciViewModels yazilimciViewModels)
        {

YazilimIsi.WebApp/Views/Yazilimci/Egitim.cshtml
@model IEnumerable<YazilimIsi.Entity.Models.Education>
@{
    ViewData["Title"] = "Egitim";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Eğitimleriniz</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="card text-center">
            <div class="card-body">
                <h3>Aldığınız Eğitimler Listesi</h3>
                <hr />
                <table class="table table-bordered table-striped table-responsive-sm">
                    <thead>
                        <tr>
                            <th scope="col">Numara</th>
                            <th scope="col">Başlık</th>
                            <th scope="col">Başlangıç Tarihi</th>
                            <th scope="col">Bitiş Tarihi</th>
                            <th scope="col">İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <th>@item.Id</th>
                                <td>
                                    @if (item.Title.Length > 30)
                                    {
                                        @item.Title.Substring(0, 29) <span>...</span>
                                    }
                                    else
                                    {
                                        @item.Title
                                    }
                                </td>
                                <td>@item.StartDate</td>
                                <td>@item.EndDate</td>
                                <td>
                                    <a href="/Yazilimci/EgitimDetay/@item.Id" class="btn btn-outline-info btn-sm">İncele</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Yazilimci/EgitimDetay.cshtml
@model YazilimIsi.Entity.Models.Education
@{
    ViewData["Title"] = "EgitimDetay";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Eğitim Detayı İnceleme</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="card text-center">
            <div class="card-body">
                <h3>Eğitim Detayı</h3>
                <hr />
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Eğitim Başlık</td>
                            <td>@Model.Title</td>
                        </tr>
                        <tr>
                            <td>Eğitim Başlangıç Tarihi</td>
                            <td>@Model.StartDate</td>
                        </tr>
                        <tr>
                            <td>Eğitim Bitiş Tarihi</td>
                            <td>@Model.EndDate</td>
                        </tr>
                        <tr>
                            <td>Eğitim Alan Geliştirici</td>
                            <td>@Model.Developer.Name @Model.Developer.Surname</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>Eğitim Açıklama Yazısı</h3>
                <hr />
                <p>@Model.Description</p>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>İşlemler</h3>
                <hr />
                <a href="" data-toggle="modal" data-target="#modalEgitimDuzenle" class="genric-btn info-border">Eğitim Düzenle</a><br /><br />
                <a href="/Yazilimci/EgitimSil/@Model.Id" class="genric-btn danger-border">Eğitim Sil</a><br /><br />
            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->
<!-- Modal -->
<div class="modal fade" id="modalEgitimDuzenle" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eğitim Düzenle</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Bu Eğitimi Gerçekten Düzenlemek İstiyor Musun?
            </div>
            <div class="modal-footer">
                <div class="container">
                    <form asp-controller="Yazilimci" asp-action="EgitimDuzenle" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <input asp-for="Title" type="text" class="form-control" value="@Model.Title" required />
                        </div>
                        <div class="form-group">
                            <div class="input-group date" data-provide="datepicker">
                                <input type="text" asp-for="StartDate" value="@Model.StartDate" readonly class="form-control" required>
                                <div class="input-group-addon">
                                    <span class="glyphicon glyphicon-th"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group date" data-provide="datepicker">
                                <input type="text" asp-for="EndDate" value="@Model.EndDate" readonly class="form-control" required>
                                <div class="input-group-addon">
                                    <span class="glyphicon glyphicon-th"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <textarea asp-for="Description" class="form-control" rows="6" minlength="10" required>@Model.Description</textarea>
                        </div>
                        <button type="button" class="genric-btn danger" data-dismiss="modal">Kapat</button>
                        <button type="submit" class="genric-btn info">Eğitim Düzenle</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            format: 'mm/dd/yyyy',
            language: 'tr',
        });
    });
</script>

YazilimIsi.WebApp/Views/Yazilimci/FotografDuzenle.cshtml
@model YazilimIsi.Entity.Models.Developer
@{
    ViewData["Title"] = "FotografDuzenle";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Fotoğraf Düzenleme Sayfası</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        @if (TempData["UpdateErrorMessage"] != null)
        {
            <blockquote class="generic-blockquote">@TempData["UpdateErrorMessage"]</blockquote>
        }

        <div class="row text-center">

            <div class="col-md-4">

                <!-- Uye Profil Fotografi -->
                <div class="card">
                    <img class="card-img-top" src="~/ImagesDeveloper/@Model.Photo" alt="@Model.Username" />
                    <div class="card-body">

                        <a href="/Yazilimci/ProfilDuzenle/" class="genric-btn info-border">Profili Düzenle</a>

                    </div>
                </div>
                <br />
                <!-- Bakiye Ve Para Yükleme -->
                <div class="card">
                    <div class="card-body">

                        <h3>Bakiye</h3>
                        <hr />

                        <p>@Model.Money TL</p>

                        <a href="#" class="genric-btn info-border">Para Yükleme</a> <br /><br />
                        <a href="/Yazilimci/HesapHareketleri/" class="genric-btn info-border">Hesap Hareketlerini İncele</a>

                    </div>
                </div>
            </div>
            <div class="col-md-8">

                <!-- TEMEL PROFIL DUZENLEME -->
                <div class="card">
                    <div class="card-body">

                        <h3>Temel Profil Bilgileri</h3>
                        <hr />

                        <form asp-controller="Yazilimci" asp-action="FotografDuzenle" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                            <div class="form-group col-md-8 mx-auto">
                                <label>Yazilimci Aktif Fotoğraf</label><br />
                                <img src="~/ImagesDeveloper/@Model.Photo" width="250" />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>Yazilimci Aktif Fotoğraf İsmi</label>
                                <input class="form-control" type="text" value="@Model.Photo" readonly />
                            </div>
                            <div class="form-group col-md-8 mx-auto">
                                <label>Yazilimci Yeni Fotoğraf</label>
                                <input class="form-control" type="file" name="Image" required />
                                <small>* Lütfen Yeni Yüklenecek Fotoğrafınızı Seçiniz.</small>
                            </div>
                            <button type="submit" class="genric-btn info-border">Fotoğrafı Güncelle</button>
                        </form>
                        <br />
                    </div>
                </div>
                <br />


            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

YazilimIsi.WebApp/Views/Yazilimci/OdulDetay.cshtml
@model YazilimIsi.Entity.Models.Award
@{
    ViewData["Title"] = "OdulDetay";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Ödül Detayı İnceleme</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="card text-center">
            <div class="card-body">
                <h3>Ödül Detayı</h3>
                <hr />
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Ödül Başlık</td>
                            <td>@Model.Title</td>
                        </tr>
                        <tr>
                            <td>Ödül Verilme Tarihi</td>
                            <td>@Model.Date</td>
                        </tr>
                        <tr>
                            <td>Ödül Alan Geliştirici</td>
                            <td>@Model.Developer.Name @Model.Developer.Surname</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>Ödül Açıklama Yazısı</h3>
                <hr />
                <p>@Model.Description</p>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>İşlemler</h3>
                <hr />
                <a href="" data-toggle="modal" data-target="#modalOdulDuzenle" class="genric-btn info-border">Ödül Düzenle</a><br /><br />
                <a href="/Yazilimci/OdulSil/@Model.Id" class="genric-btn danger-border">Ödül Sil</a><br /><br />
            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->
<!-- Modal -->
<div class="modal fade" id="modalOdulDuzenle" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ödül Düzenle</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Bu Ödülü Gerçekten Düzenlemek İstiyor Musun?
            </div>
            <div class="modal-footer">
                <div class="container">
                    <form asp-controller="Yazilimci" asp-action="OdulDuzenle" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <input asp-for="Title" type="text" class="form-control" value="@Model.Title" required />
                        </div>
                        <div class="form-group">
                            <div class="input-group date" data-provide="datepicker">
                                <input type="text" asp-for="Date" value="@Model.Date" readonly class="form-control" required>
                                <div class="input-group-addon">
                                    <span class="glyphicon glyphicon-th"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <textarea asp-for="Description" class="form-control" rows="6" minlength="10" required>@Model.Description</textarea>
                        </div>
                        <button type="button" class="genric-btn danger" data-dismiss="modal">Kapat</button>
                        <button type="submit" class="genric-btn info">Ödül Düzenle</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            format: 'mm/dd/yyyy',
            language: 'tr',
        });
    });
</script>

YazilimIsi.WebApp/Views/Yazilimci/PortfolyoDetay.cshtml
@model YazilimIsi.Entity.Models.Portfolio
@{
    ViewData["Title"] = "PortfolyoDetay";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div classNedir="bradcam_text">
                    <h3>Portfolyo Detayı İnceleme</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="container">

        <div class="card text-center">
            <div class="card-body">
                <h3>Portfolyo Detayı</h3>
                <hr />
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>Proje Adı</td>
                            <td>@Model.ProjectName</td>
                        </tr>
                        <tr>
                            <td>Proje Tarihi</td>
                            <td>@Model.CreatedDate</td>
                        </tr>
                        <tr>
                            <td>Proje Url Adresi</td>
                            <td>@Model.ProjectUrl</td>
                        </tr>
                        <tr>
                            <td>Proje Geliştirici</td>
                            <td>@Model.Developer.Name @Model.Developer.Surname</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>Portfolyo Açıklama Yazısı</h3>
                <hr />
                <p>@Model.Description</p>
            </div>
        </div>
        <br />
        <div class="card text-center">
            <div class="card-body">
                <h3>İşlemler</h3>
                <hr />
                <a href="" data-toggle="modal" data-target="#modalPortfolyoDuzenle" class="genric-btn info-border">Portfolyo Düzenle</a><br /><br />
                <a href="/Yazilimci/PortfolyoSil/@Model.Id" class="genric-btn danger-border">Portfolyo Sil</a><br /><br />
            </div>
        </div>

    </div>
</div>
<!-- featured_candidates_area_end  -->

<!-- Modal -->
<div class="modal fade" id="modalPortfolyoDuzenle" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Portfolyo Düzenle</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Bu Portfolyoyu Gerçekten Düzenlemek İstiyor Musun?
            </div>
            <div class="modal-footer">
                <div class="container">
                    <form asp-controller="Yazilimci" asp-action="PortfolyoDuzenle" asp-route-Id="@Model.Id" method="post" enctype="multipart/form-data">
                        <div class="form-group">
                            <input asp-for="ProjectName" type="text" class="form-control" value="@Model.ProjectName" required />
                        </div>
                        <div class="form-group">
                            <div class="input-group date" data-provide="datepicker">
                                <input type="text" asp-for="CreatedDate" value="@Model.CreatedDate" readonly class="form-control" required>
                                <div class="input-group-addon">
                                    <span class="glyphicon glyphicon-th"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <input asp-for="ProjectUrl" type="text" class="form-control" value="@Model.ProjectUrl" required />
                        </div>
                        <div class="form-group">
                            <textarea asp-for="Description" class="form-control" rows="6" minlength="10" required>@Model.Description</textarea>
                        </div>
                        <button type="button" class="genric-btn danger" data-dismiss="modal">Kapat</button>
                        <button type="submit" class="genric-btn info">Portfolyo Düzenle</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.datepicker').datepicker({
            format: 'mm/dd/yyyy',
            language: 'tr',
        });
    });
</script>

YazilimIsi.WebApp/Views/Yazilimci/Profil.cshtml
@{
    ViewData["Title"] = "Profil";
    Layout = "~/Views/Shared/_LayoutMain.cshtml";
}

<h2>Profil</h2>